# Github Actions CI Pipeline
name: CI/CD pipeline for HypeHub

# When? 
# on every push and pull request to 'main'
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  types:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/types

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build types package
        run: pnpm run build

  client:
    needs: types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint 

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  verify:
    needs: [types, client]
    runs-on: ubuntu-latest
    steps:
      - name: Verify CI
        run: echo "All checks passed"

# TODO: Add server job when WebSocket server is implemented
# - Build and test server
# - Docker image creation
# - Container deployment

# TODO: Add infrastructure job when Terraform configs are ready
# - Terraform validation
# - Infrastructure deployment

